# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'luxsu.ui',
# licensing of 'luxsu.ui' applies.
#
# Created: Thu May  2 16:35:44 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 35))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.stopBtn = QtWidgets.QPushButton(self.frame)
        self.stopBtn.setObjectName("stopBtn")
        self.gridLayout_3.addWidget(self.stopBtn, 0, 3, 1, 1)
        self.renBtn = QtWidgets.QPushButton(self.frame)
        self.renBtn.setObjectName("renBtn")
        self.gridLayout_3.addWidget(self.renBtn, 0, 1, 1, 1)
        self.inBtn = QtWidgets.QPushButton(self.frame)
        self.inBtn.setObjectName("inBtn")
        self.gridLayout_3.addWidget(self.inBtn, 0, 4, 1, 1)
        self.pauBtn = QtWidgets.QPushButton(self.frame)
        self.pauBtn.setObjectName("pauBtn")
        self.gridLayout_3.addWidget(self.pauBtn, 0, 2, 1, 1)
        self.saveBtn = QtWidgets.QPushButton(self.frame)
        self.saveBtn.setObjectName("saveBtn")
        self.gridLayout_3.addWidget(self.saveBtn, 0, 6, 1, 1)
        self.outBtn = QtWidgets.QPushButton(self.frame)
        self.outBtn.setObjectName("outBtn")
        self.gridLayout_3.addWidget(self.outBtn, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 7, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 490))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.renderView = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderView.sizePolicy().hasHeightForWidth())
        self.renderView.setSizePolicy(sizePolicy)
        self.renderView.setText("")
        self.renderView.setScaledContents(True)
        self.renderView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.renderView.setObjectName("renderView")
        self.gridLayout_2.addWidget(self.renderView, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuLoad_File = QtWidgets.QMenu(self.menubar)
        self.menuLoad_File.setObjectName("menuLoad_File")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionZoom_In_25_Ctrl = QtWidgets.QAction(MainWindow)
        self.actionZoom_In_25_Ctrl.setObjectName("actionZoom_In_25_Ctrl")
        self.actionZoom_In_25_Ctrl_2 = QtWidgets.QAction(MainWindow)
        self.actionZoom_In_25_Ctrl_2.setObjectName("actionZoom_In_25_Ctrl_2")
        self.actionNormal_Size_Ctrl_s = QtWidgets.QAction(MainWindow)
        self.actionNormal_Size_Ctrl_s.setObjectName("actionNormal_Size_Ctrl_s")
        self.fitToWindowAct = QtWidgets.QAction(MainWindow)
        self.fitToWindowAct.setCheckable(True)
        self.fitToWindowAct.setObjectName("fitToWindowAct")
        self.actionLoad_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_File.setObjectName("actionLoad_File")
        self.actionSave_Scene = QtWidgets.QAction(MainWindow)
        self.actionSave_Scene.setObjectName("actionSave_Scene")
        self.actionSave_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuLoad_File.addAction(self.actionLoad_File)
        self.menuLoad_File.addAction(self.actionSave_Scene)
        self.menuLoad_File.addAction(self.actionSave_Image)
        self.menuLoad_File.addSeparator()
        self.menuLoad_File.addAction(self.actionExit)
        self.menuView.addAction(self.actionZoom_In_25_Ctrl)
        self.menuView.addAction(self.actionZoom_In_25_Ctrl_2)
        self.menuView.addAction(self.actionNormal_Size_Ctrl_s)
        self.menuView.addAction(self.fitToWindowAct)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuLoad_File.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "LuxSu Viewer", None, -1))
        self.stopBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.renBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Render", None, -1))
        self.inBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom In", None, -1))
        self.pauBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.saveBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Save Image", None, -1))
        self.outBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom Out", None, -1))
        self.menuLoad_File.setTitle(QtWidgets.QApplication.translate("MainWindow", "Load File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionZoom_In_25_Ctrl.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom In (25%) Ctrl+ +", None, -1))
        self.actionZoom_In_25_Ctrl.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl++", None, -1))
        self.actionZoom_In_25_Ctrl_2.setText(QtWidgets.QApplication.translate("MainWindow", "ZoomOut (25%) Ctrl+ -", None, -1))
        self.actionZoom_In_25_Ctrl_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+-", None, -1))
        self.actionNormal_Size_Ctrl_s.setText(QtWidgets.QApplication.translate("MainWindow", "Normal Size Ctrl+ s", None, -1))
        self.actionNormal_Size_Ctrl_s.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.fitToWindowAct.setText(QtWidgets.QApplication.translate("MainWindow", "Fit To Window Ctrl+f", None, -1))
        self.fitToWindowAct.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+F", None, -1))
        self.actionLoad_File.setText(QtWidgets.QApplication.translate("MainWindow", "Load File", None, -1))
        self.actionSave_Scene.setText(QtWidgets.QApplication.translate("MainWindow", "Save Scene", None, -1))
        self.actionSave_Image.setText(QtWidgets.QApplication.translate("MainWindow", "Save Image", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

